#### Задание 1

In [70]:
import numpy as np

In [71]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [72]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

#### Задание 2

In [73]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [74]:
col1 = a_centered[:, 0]
col2 = a_centered[:, 1]
a_centered_sp = np.dot(col1, col2)
a_centered_sp

8.0

In [75]:
result = a_centered_sp / (a.shape[0] - 1)
result

2.0

#### Задание 4

In [78]:
covar_a = np.cov(a.T)
covar_a

array([[1. , 2. ],
       [2. , 4.3]])